name: UAT
on:
  push:
    tags:
      - 'uat-*'

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: always() 
    steps:
      - name: Set job status
        id: job-status
        run: echo "::set-output name=status::${{ job.status }}"
  
      - name: Send Slack notification
        uses: slack/webhook-action@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_DEBUG }}
          text: |
            *Job Name:* ${{ github.workflow }} - ${{ github.job }}
            *Date:* $(date)
            *Status:* ${{ steps.job-status.outputs.status }}
          channel: '#test-prod-releases'
