name: UAT
on:
  push:
    tags:
      - 'uat-*'
jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: always() 
    steps:
      - name: Set job status
        id: job-status
        run: echo "::set-output name=status::${{ job.status }}"
  
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ steps.job-status.outputs.status }}
          channel: '#test-prod-releases'
          text: |
            *Job Name:* ${{ github.workflow }} - ${{ github.job }}
            *Date:* $(date)
            *Status:* ${{ steps.job-status.outputs.status }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
