name: UAT
on:
  push:
    tags:
      - 'uat-*'

jobs:
  ui:
    name: UI 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Run UI Deployment Workflow
        id: ui_workflow
        uses: ./.github/workflows/ui-deployment.yml
        continue-on-error: true

      - name: Store UI Job Status
        if: always()
        run: echo "${{ job.status }}" > ui_job_status.txt

      - name: Upload UI Job Status Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ui-job-status
          path: ui_job_status.txt

  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: ui
    if: always()
    steps:
      - name: Download UI Job Status Artifact
        uses: actions/download-artifact@v2
        with:
          name: ui-job-status
          path: ./ui_job_status
      
      - name: Set color based on job status
        id: set-color
        run: echo "::set-output name=color::$(if [ '$(cat ./ui_job_status/ui_job_status.txt)' == 'success' ]; then echo 'good'; else echo 'danger'; fi)"
      
      - name: Get current date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Set emoji based on job status
        id: set-emoji
        run: echo "::set-output name=emoji::$(if [ '$(cat ./ui_job_status/ui_job_status.txt)' == 'success' ]; then echo ':60fps_parrot:'; else echo ':alert:'; fi)"

      - name: Send Slack notification
        run: |
          status=$(cat ./ui_job_status/ui_job_status.txt)
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "${{ steps.set-color.outputs.color }}",
                "pretext": "*Job Name:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} - ${{ github.job }}>",
                "text": "*Date:* ${{ steps.get-date.outputs.date }}\n*Status:* $status ${{ steps.set-emoji.outputs.emoji }}"
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_DEBUG }}
    

          
