name: UAT
on:
  push:
    tags:
      - 'uat-*'

jobs:

  fail_job:
    name: Fail Job
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Fail the job
        run: exit 1

  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: fail_job
    if: always() 
    steps:
      - name: Set job status
        id: job-status
        run: echo "::set-output name=status::${{ needs.fail_job.outputs.status }}"
      
      - name: Set color based on job status
        id: set-color
        run: echo "::set-output name=color::$(if [ '${{ needs.fail_job.outputs.status }}' == 'success' ]; then echo 'good'; else echo 'danger'; fi)"
      
      - name: Get current date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Set emoji based on job status
        id: set-emoji
        run: echo "::set-output name=emoji::$(if [ '${{ needs.fail_job.outputs.status }}' == 'success' ]; then echo ':parrot:'; else echo ':alert:'; fi)"

      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "${{ steps.set-color.outputs.color }}",
                "pretext": "*Job Name:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} - ${{ github.job }}>",
                "text": "*Date:* ${{ steps.get-date.outputs.date }}\n*Status:* ${{ steps.job-status.outputs.status }} ${{ steps.set-emoji.outputs.emoji }}"
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_DEBUG }}