name: UAT
on:
  push:
    tags:
      - 'uat-*'

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    if: always() 
    steps:
      - name: Set job status
        id: job-status
        run: echo "::set-output name=status::${{ job.status }}"
      
      - name: Set color based on job status
        id: set-color
        run: echo "::set-output name=color::$(if [ '${{ job.status }}' == 'success' ]; then echo 'good'; else echo 'danger'; fi)"
      
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "${{ steps.set-color.outputs.color }}",
                "pretext": "*Job Name:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} - ${{ github.job }}>",
                "text": "*Date:* $date\n*Status:* ${{ steps.job-status.outputs.status }}"
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_DEBUG }}