name: UAT
on:
  push:
    tags:
      - 'uat-*'

jobs:
  fail_job:
    name: Fail Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fail the job
        run: exit 0